"""Autonomous Grid'5000 operator contracts."""

from osm_polygon_sentence_relevance.operator.config import (
    DATA_ROOT,
    DEFAULT_BATCH_SIZE,
    DEFAULT_LABEL_MODEL_FILE,
    DEFAULT_LABEL_MODEL_FILE_SHA256,
    DEFAULT_LABEL_MODEL_REPO_ID,
    DEFAULT_LABEL_MODEL_REVISION,
    DEFAULT_LLAMA_PARALLEL,
    DEFAULT_LLAMA_PER_SLOT_CONTEXT,
    DEFAULT_ROW_LIMIT,
    DEFAULT_TOKENIZER_REPO_ID,
    DEFAULT_TOKENIZER_REVISION,
    INPUT_DATASET_ID,
    OUTPUT_DATASET_ID,
    SUPPORTED_LLAMA_PARALLEL,
    Grid5000Requirements,
    OperatorConfig,
    RunIdentity,
    Scope,
    Stage,
)
from osm_polygon_sentence_relevance.operator.earliest_start import (
    IMMEDIATE_START_LIMIT,
    ReplacementCandidate,
    rank_replacement_candidates,
    should_seek_replacement,
)
from osm_polygon_sentence_relevance.operator.quota import (
    QuotaError,
    QuotaUsage,
    parse_quota_output,
)
from osm_polygon_sentence_relevance.operator.ssh import (
    LogChunk,
    SshClient,
    SshConnectionError,
    SshError,
    SshProtocolError,
    SshRemoteError,
    SshResult,
    SshTimeoutError,
)
from osm_polygon_sentence_relevance.operator.state import (
    RunPhase,
    RunState,
    StateError,
    StateIdentityMismatch,
    StateSecurityError,
    StateStore,
    StateTransitionError,
)

__all__ = [
    "DATA_ROOT",
    "IMMEDIATE_START_LIMIT",
    "INPUT_DATASET_ID",
    "OUTPUT_DATASET_ID",
    "Scope",
    "Stage",
    "Grid5000Requirements",
    "RunIdentity",
    "OperatorConfig",
    "ReplacementCandidate",
    "QuotaError",
    "QuotaUsage",
    "RunState",
    "RunPhase",
    "StateStore",
    "StateError",
    "StateIdentityMismatch",
    "StateTransitionError",
    "parse_quota_output",
    "rank_replacement_candidates",
    "should_seek_replacement",
    "StateSecurityError",
    "LogChunk",
    "SshClient",
    "SshError",
    "SshResult",
    "SshConnectionError",
    "SshRemoteError",
    "SshTimeoutError",
    "SshProtocolError",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_ROW_LIMIT",
    "DEFAULT_LLAMA_PARALLEL",
    "DEFAULT_LLAMA_PER_SLOT_CONTEXT",
    "SUPPORTED_LLAMA_PARALLEL",
    "DEFAULT_LABEL_MODEL_REPO_ID",
    "DEFAULT_LABEL_MODEL_REVISION",
    "DEFAULT_LABEL_MODEL_FILE",
    "DEFAULT_LABEL_MODEL_FILE_SHA256",
    "DEFAULT_TOKENIZER_REPO_ID",
    "DEFAULT_TOKENIZER_REVISION",
]
